# Generated by Django 6.0.2 on 2026-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.FileField(default=None, unique=True, upload_to='slider_img/')),
                ('discount_deal', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('NEW ARRIVAL', 'NEW ARRIVAL')], max_length=300)),
                ('discount', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
